apiVersion: v1
kind: ConfigMap
metadata:
  name: chatapp-config
  namespace: chatapp
data:
  NODE_ENV: "production"
  MONGO_DB_NAME: "chatapp_prod"
  JWT_EXPIRES_IN: "7d"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "https://www.chatapp.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp
type: Opaque
data:
  # Base64 encoded values
  MONGO_ROOT_USER: Y2hhdGFwcF9hZG1pbg== # chatapp_admin
  MONGO_ROOT_PASSWORD: U2VjdXJlTW9uZ29QYXNzd29yZDIwMjQh # SecureMongoPassword2024!
  JWT_SECRET: dWx0cmEtc2VjdXJlLWp3dC1zZWNyZXQta2V5LXByb2R1Y3Rpb24tMjAyNA==
  REDIS_PASSWORD: U2VjdXJlUmVkaXNQYXNzd29yZDIwMjQh # SecureRedisPassword2024!
